"""add status

Revision ID: 26b67dce3530
Revises: d4565f2a89a1
Create Date: 2020-04-26 00:34:21.886692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26b67dce3530'
down_revision = 'd4565f2a89a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donation_group', sa.Column('order_status', sa.Enum('pending', 'verified', 'received', name='orderstatus'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('donation_group', 'order_status')
    # ### end Alembic commands ###
