"""add fulfill field

Revision ID: 2da9e77650b6
Revises: e48efb53cf05
Create Date: 2020-05-05 01:04:55.117835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2da9e77650b6'
down_revision = 'e48efb53cf05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request_status', sa.Column('units', sa.Integer(), nullable=True))
    op.add_column('single_request', sa.Column('current_status', sa.Enum('requested', 'looking', 'matched', 'sent', 'completed', name='requeststatustype'), nullable=True))
    op.add_column('single_request', sa.Column('fulfilled', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('single_request', 'fulfilled')
    op.drop_column('single_request', 'current_status')
    op.drop_column('request_status', 'units')
    # ### end Alembic commands ###
