"""add pledges

Revision ID: 3af4aaa7ef34
Revises: 8152eb605e8a
Create Date: 2020-05-24 00:48:50.663524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3af4aaa7ef34'
down_revision = '8152eb605e8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pledge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('pledger_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pledger_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['single_request.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pledge')
    # ### end Alembic commands ###
