"""add completed field

Revision ID: 4dc8f9e0ce7a
Revises: 2da9e77650b6
Create Date: 2020-05-06 00:56:14.920051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dc8f9e0ce7a'
down_revision = '2da9e77650b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('single_request', sa.Column('completed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('single_request', 'completed')
    # ### end Alembic commands ###
