"""add pledge confirmation

Revision ID: 6ee1823d2983
Revises: 3af4aaa7ef34
Create Date: 2020-05-24 12:33:10.946617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ee1823d2983'
down_revision = '3af4aaa7ef34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pledge', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pledge', 'confirmed')
    # ### end Alembic commands ###
