"""add request timestamp

Revision ID: 8152eb605e8a
Revises: 1b933de5b69a
Create Date: 2020-05-16 22:58:39.195484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8152eb605e8a'
down_revision = '1b933de5b69a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('single_request', sa.Column('request_timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('single_request', 'request_timestamp')
    # ### end Alembic commands ###
