"""add verified by

Revision ID: a9b02ffedfb7
Revises: 4dc8f9e0ce7a
Create Date: 2020-05-09 16:30:44.861974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9b02ffedfb7'
down_revision = '4dc8f9e0ce7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verifications',
    sa.Column('verified_id', sa.Integer(), nullable=True),
    sa.Column('verifier_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['verified_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verifier_id'], ['user.id'], ondelete='CASCADE')
    )
    op.add_column('user', sa.Column('verified_tag', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'verified_tag')
    op.drop_table('verifications')
    # ### end Alembic commands ###
