"""add info to supply type

Revision ID: b9759c9d33bb
Revises: 59496d216729
Create Date: 2020-04-18 02:07:19.652576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9759c9d33bb'
down_revision = '59496d216729'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supply_type', sa.Column('info', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('supply_type', 'info')
    # ### end Alembic commands ###
