"""add region to hospital

Revision ID: e59d93cab7d5
Revises: b9759c9d33bb
Create Date: 2020-04-19 01:10:47.727851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e59d93cab7d5'
down_revision = 'b9759c9d33bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hospital', sa.Column('region', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hospital', 'region')
    # ### end Alembic commands ###
